name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello :) Thanks for reporting the issue. We will look into it soon'' first issue'
        pr-message: 'Hello :) Thanks for contributing to this repo. Your PR will be approved soon'' first pr'
