name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue needs to be worked upon soon. @SumanjaliDamarla, @SushmaBarma please have a look into it'
        stale-pr-message: 'This PR needs to be merged / changed as soon as possible. @SumanjaliDamarla, @SushmaBarma please have a look into it'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
